[book]
authors = ["dingtang"]
language = "zh-CN"
multilingual = false
src = "src"
title = "AUTOSAR中文计划"


[output.html]
cname = "autosar.ltd"
additional-css = ["theme/style3.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/dingtang2008/dingtang2008.github.io/"
edit-url-template = "https://github.com/dingtang2008/dingtang2008.github.io/edit/main/{path}"